name: aqgeo-2024-potential-fields
channels:
  - conda-forge
dependencies:
  - python==3.12.*
  - pip
  # For slides
  - livereload
  # IPython and Jupyter
  - ipython
  - jupyter
  - jupyterlab
  - nbdime # git diffs for notebooks
  - nbqa
  - jupytext
  # Packages
  - ipywidgets
  - numpy==2.*.*
  - simpeg==0.23.0
  - choclo==0.3.0
  - pandas==2.2.*
  - matplotlib
